### PR TITLE
Update Damages.cs

### PR DESCRIPTION
**Pull request by fukuhara1995**

### CODE REVIEW

**Comment by Hellsing** [comment]
Your latest commit would break the addon.

**Comment by Hellsing** [comment]
Also, if you want to update the damage values, please provide a source where you got the damage values from, thanks.

**Comment by fukuhara1995** [comment]
hi, i am vietnamese so I'm not proficient in English. i am using your addon and nebula kalista  of goldfinsh. I have seen difference of Rend's damage. 
[E] damage % of his(her) addon =100% and killed target while dame percent info of your addon <100%.,
Please check my problems.  thank you!!!

**Comment by fukuhara1995** [comment]
https://www.reddit.com/r/leagueoflegends/comments/3boxu4/math_on_the_tentative_pbe_kalista_changes/.
Thank you!!!!

**Pull request closed without merging**
